name 'djshop_ubuntu'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures djshop_ubuntu'
long_description 'Installs/Configures djshop_ubuntu'
version '0.1.0'

depends 'apt', '~> 4.0.1'
depends 'firewall', '~> 2.5.2'
depends 'nginx_conf', '~> 1.0.1'
depends 'mysql', '~> 7.2.0'
depends 'application_python', '~> 4.0.0'
depends 'mysql2_chef_gem', '~> 1.1.0'
depends 'database', '~> 5.1.2'
